export const environment = {
  production: true,
  apiUrl: '/api/inventory',
  docUrl: '/api/document',
  loginUrl: '/api/um',
  homeUrl: '/',
  portalUrl: '/api/portal',
  receivePrefix: 'REV',
  borrowPrefix: 'BOR',
  returningPrefix: 'RET',
  requisitionPrefix: 'REQ',
  issuePrefix: 'INS',

  purchasingUrl: '/purchasing/#/',
  planningUrl: '/planning/#/',
  inventoryUrl: '/',
  materialsUrl: '/material/#/',
  umUrl: '/um/#/',
  contractsUrl: '/contracts/#/',
  reportUrl: '/reports/#/',
};
